-- Agent Namer: persist the chosen English name + title for each (sub)agent in the workforce.
-- Generated by the AgentNamer Orq.ai agent; confirmed via the web UI.

create table if not exists public.agent_names (
  id uuid primary key default gen_random_uuid(),

  -- Stable identifier for the agent we are naming. Typically the Orq.ai agent
  -- key (e.g. "AgentNamer") but any string that uniquely identifies the agent
  -- in our workforce is fine. Exactly one active name per agent_key.
  agent_key text not null unique,

  -- What does this agent do? Feeds the Namer and useful for later browsing.
  agent_description text not null,

  -- The chosen name + metadata, mirroring the Orq agent's json_schema output.
  name text not null,
  title text not null,
  initial char(1) not null,
  domain text not null,
  rationale text not null,

  -- Optional link back to the Orq.ai agent record.
  orq_agent_id text,

  -- Who confirmed this name (user UUID from auth.users). Nullable so automated
  -- callers without a session can still persist a name.
  confirmed_by uuid references auth.users (id),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists agent_names_domain_idx on public.agent_names (domain);
create index if not exists agent_names_initial_idx on public.agent_names (initial);

-- Keep updated_at fresh on any update.
create or replace function public.agent_names_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists agent_names_touch on public.agent_names;
create trigger agent_names_touch
  before update on public.agent_names
  for each row execute function public.agent_names_touch_updated_at();

-- RLS: authenticated users can read; writes go through the service role
-- (API routes on the server). No direct insert/update from the browser.
alter table public.agent_names enable row level security;

drop policy if exists "agent_names read for authenticated" on public.agent_names;
create policy "agent_names read for authenticated"
  on public.agent_names
  for select
  to authenticated
  using (true);

comment on table public.agent_names is
  'Persisted English names for (sub)agents in the MR Automations workforce. First letter of name matches the agent domain (S=Sales, D=Debtor, etc.). Generated by the AgentNamer Orq.ai agent.';
